[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
macrob2b_token = "Hs5A3fAN5GpEVpHPSZtmAix8RPf171Ry89EQQkVtoVwP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sadeq/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
